pipeline {
    agent any
    
    tools {
    jdk 'jdk8_update221'
    }
    stages {
        stage('Clone') {
            steps {
                sh "rm -rf *"
                sh "git clone https://github.com/karimFSL/jenkins-tuto"
                sh "ls -alt /opt"
            }
        }


        stage('Build') {
            steps {
                sh "java -version"
                sh "cd jenkins-tuto/tuto-jenkins-1 && javac Main.java"
            }
        }


        stage('Run') {
            steps {
                sh "cd jenkins-tuto/tuto-jenkins-1 && java Main"
            }
        }
    }
}
